### ISSUE TITLE
Automate updating of the geoip database

### ISSUE THREAD

**Issue by timja** [olblak/mirrorbits#1]
Had a user complain that the DB is out of date

It looks like it hasn't run been updated in ~7months

cc @olblak

**Comment by olblak** [comment]
The database is generated during the docker image build (multi stage) we just have to regularly build the image from infra.ci

**Comment by timja** [comment]
I think I have a different solution based on https://hub.docker.com/r/maxmindinc/geoipupdate and running it as another container in the pod

setting the GEOIPUPDATE_FREQUENCY to be something like a week.

**Comment by timja** [comment]
PR here https://github.com/jenkins-infra/charts/pull/449,

Maybe we should remove the geoip data from this image and just always populate it from the helm chart?
